version: "3.9"
services:

    # PHP service
    app:
        restart: always
        build:
            context: ./deploy/php
        container_name: src-app
        working_dir: /var/www/
        volumes:
            - ./:/var/www
            - ./deploy/php/xdebug.ini:/usr/local/etc/php/conf.d/xdebug.ini
        networks:
            - app-network

    # Nginx service
    nginx:
        restart: always
        build: "./deploy/nginx"
        container_name: src-nginx
        ports:
            - "8080:80"
        volumes:
            - ./:/var/www
            - ./deploy/nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf
        networks:
            - app-network

networks:
    app-network:
        driver: bridge
